### ISSUE TITLE
Will it be beneficial to transfer weights of the discriminator to the segmentation task?

### ISSUE THREAD

**Issue by tea321000** [boschresearch/unetgan#6]
Hi,

Is it beneficial to transfer weights of the discriminator, which uses a U-net-like structure, to the segmentation task? On the other hand, is it possible to transform U-net segmentation network into unetgan, even if it uses batch normalization, which destabilizes the GAN?

I am looking forward to your reply.

Sincerely,
tea

**Comment by edgarschnfld** [comment]
Hi,

For your first question: I can imagine that transferring the discriminator weights for segmentation will work well. After all, something like this has recently been shown to be very beneficial even for a normal discriminator:
https://github.com/bryandlee/repurpose-gan 
https://arxiv.org/abs/2103.04379

For the second question: If you want to use an existing segmentation net as a U-Net discriminator, I would advise removing the batch normalization. Further, you should add spectral normalization to the segmenter, which will greatly stabilize training.  

Best, 
Edgar

**Comment by tea321000** [comment]
Thank for your reply.
